repos:
- repo: local
  hooks:
    - id: terraform_docs
      name: Check if terraform module README should be updated
      entry: bash ./terraform-docs-hook.sh
      language: system
      pass_filenames: false

