---
name: '🔥 Infra deployment workflow'

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
      - fix/*
      - main

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  TERRAFORM_VERSION: 1.3.8

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        layer: [ 'network', 'ecs_cluster' ,'load_balancer', 'ecs_task_definition', 'tg', 'listener' ]
      max-parallel: 1
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true
    steps:
      - uses: actions/checkout@v3

      - name: terraform plan and validate
        uses: ./.github/actions/ims-plan-and-validate
        with:
          ENV_ID: 'd'
          environment: 'dev'
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          layer: ${{ matrix.layer }}

      - name: terraform apply
        uses: ./.github/actions/ims-tf-apply
        with:
          ENV_ID: 'd'
          environment: 'dev'
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          layer: ${{ matrix.layer }}
